version: "3.9"

services:
    database:
        image: postgres
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - ./data/db:/var/lib/postgresql/data
        hostname: database
    backend:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
#        entrypoint: ./entrypoint.sh
        ports:
            - "8000:8000"
        depends_on:
            - database
            - rabbit
        volumes:
            - .:/code
    rabbit:
        image: rabbitmq
        ports:
            - "5672:5672"
        environment:
            - RABBITMQ_DEFAULT_USER=rabbit
            - RABBITMQ_DEFAULT_PASS=rabbit
        hostname: rabbitmq
    celery_worker:
        build: .
        command: celery -A financeapp worker -l info
        depends_on:
            - backend
            - rabbit
    celery_beat:
        build: .
        command: celery -A financeapp beat -l info
        depends_on:
            - backend
            - rabbit