# Generated by Django 3.2.6 on 2021-08-20 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(max_length=36, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('published_date', models.DateTimeField()),
                ('link', models.URLField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('symbol', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['created'],
            },
        )
    ]
